repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/dbt-checkpoint/dbt-checkpoint
  rev: v1.2.1
  hooks:
  # Script checks
  - id: check-script-semicolon
  # Model checks
  - id: check-model-has-properties-file
    name: Check property file exist for each model
    files: ^models/
    exclude: ^models/semantic_layer/saved_queries
  - id: check-model-has-description
    name: Check the model has a description
    files: ^models/
    exclude: ^models/semantic_layer/saved_queries
  - id: check-model-has-all-columns
    name: Check model has all columns in property file
    files: ^models/
    exclude: ^models/semantic_layer/saved_queries
  - id: check-column-name-contract
    name: Check some column names follow a regex
    files: ^models/
    args: [--pattern, "(.*_)?(is|are|has|do|does|did|can|uses)_.+", --dtype, BOOL]
  - id: check-column-desc-are-same
    name: Check all the models have the same descriptions for the same column names
    files: ^models/
- repo: local
  hooks:
    - id: sqlfluff-lint
      name: sqlfluff-lint
      entry: poetry run sqlfluff lint
      language: system
    - id: sqlfluff-fix
      name: sqlfluff-fix
      entry: poetry run sqlfluff fix
      language: system
