name: 'qualifyze'
version: '1.0.0'
config-version: 2

profile: 'qualifyze'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  qualifyze:
    bigtables:
      materialized: table
      +schema: platinum
    marts:
      materialized: table
      +schema: gold
    staging:
      materialized: view
      +schema: silver
    utilities:
      materialized: view
      +schema: silver
    semantic_layer:
      saved_queries:
        materialized: table
        +schema: gold
seeds:
  +schema: silver
tests:
  +severity: warn
